<?php

/**
 * BotInfoIdentity.
 *
 * @category Enum
 *
 * @author   Fingerprint
 *
 * @see      https://fingerprint.com
 */

/**
 * Server API.
 *
 * Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Fingerprint\ServerSdk\Model;

/**
 * The verification status of the bot's identity:
 * `verified` - well-known bot with publicly verifiable identity, directed by the bot provider.
 * `signed` - bot that signs its platform via Web Bot Auth, directed by the bot provider's customers.
 * `spoofed` - bot that claims a public identity but fails verification.
 * `unknown` - bot that does not publish a verifiable identity.
 *
 * @category Enum
 *
 * @description The verification status of the bot&#39;s identity:  * &#x60;verified&#x60; - well-known bot with publicly verifiable identity, directed by the bot provider.  * &#x60;signed&#x60; - bot that signs its platform via Web Bot Auth, directed by the bot provider&#39;s customers.  * &#x60;spoofed&#x60; - bot that claims a public identity but fails verification.  * &#x60;unknown&#x60; - bot that does not publish a verifiable identity.
 *
 * @author   Fingerprint
 *
 * @see      https://fingerprint.com
 *
 * @noinspection GrazieInspection
 * @noinspection RedundantSuppression
 */
enum BotInfoIdentity: string
{
    case VERIFIED = 'verified';
    case SIGNED = 'signed';
    case SPOOFED = 'spoofed';
    case UNKNOWN = 'unknown';
}
