<?php

/**
 * BrowserDetails.
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   Fingerprint
 *
 * @see      https://fingerprint.com
 */

/**
 * Server API.
 *
 * Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Fingerprint\ServerSdk\Model;

use Fingerprint\ServerSdk\ObjectSerializer;

/**
 * BrowserDetails Class.
 *
 * @category Class
 *
 * @author   Fingerprint
 *
 * @see      https://fingerprint.com
 *
 * @implements \ArrayAccess<string, mixed>
 *
 * @noinspection GrazieInspection
 * @noinspection RedundantSuppression
 */
class BrowserDetails implements ModelInterface, \ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     */
    protected static string $openAPIModelName = 'BrowserDetails';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static array $openAPITypes = [
        'browser_name' => 'string',
        'browser_major_version' => 'string',
        'browser_full_version' => 'string',
        'os' => 'string',
        'os_version' => 'string',
        'device' => 'string',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'browser_name' => null,
        'browser_major_version' => null,
        'browser_full_version' => null,
        'os' => null,
        'os_version' => null,
        'device' => null,
    ];

    /**
     * Array of nullable properties. Used for (de)serialization.
     *
     * @var bool[]
     */
    protected static array $openAPINullables = [
        'browser_name' => false,
        'browser_major_version' => false,
        'browser_full_version' => false,
        'os' => false,
        'os_version' => false,
        'device' => false,
    ];

    /**
     * If a nullable field gets set to null, insert it here.
     *
     * @var bool[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'browser_name' => 'browser_name',
        'browser_major_version' => 'browser_major_version',
        'browser_full_version' => 'browser_full_version',
        'os' => 'os',
        'os_version' => 'os_version',
        'device' => 'device',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static array $setters = [
        'browser_name' => 'setBrowserName',
        'browser_major_version' => 'setBrowserMajorVersion',
        'browser_full_version' => 'setBrowserFullVersion',
        'os' => 'setOs',
        'os_version' => 'setOsVersion',
        'device' => 'setDevice',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static array $getters = [
        'browser_name' => 'getBrowserName',
        'browser_major_version' => 'getBrowserMajorVersion',
        'browser_full_version' => 'getBrowserFullVersion',
        'os' => 'getOs',
        'os_version' => 'getOsVersion',
        'device' => 'getDevice',
    ];

    /**
     * Associative array for storing property values.
     */
    protected array $container = [];

    /**
     * Constructor.
     *
     * @param array|null $data Associated array of property values
     *                         initializing the model
     *
     * @noinspection DuplicatedCode
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('browser_name', $data ?? [], null);
        $this->setIfExists('browser_major_version', $data ?? [], null);
        $this->setIfExists('browser_full_version', $data ?? [], null);
        $this->setIfExists('os', $data ?? [], null);
        $this->setIfExists('os_version', $data ?? [], null);
        $this->setIfExists('device', $data ?? [], null);
    }

    /**
     * Gets the string presentation of the object.
     *
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Checks if a property is nullable.
     *
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if (null === $this->container['browser_name']) {
            $invalidProperties[] = "'browser_name' can't be null";
        }
        if (null === $this->container['browser_major_version']) {
            $invalidProperties[] = "'browser_major_version' can't be null";
        }
        if (null === $this->container['browser_full_version']) {
            $invalidProperties[] = "'browser_full_version' can't be null";
        }
        if (null === $this->container['os']) {
            $invalidProperties[] = "'os' can't be null";
        }
        if (null === $this->container['os_version']) {
            $invalidProperties[] = "'os_version' can't be null";
        }
        if (null === $this->container['device']) {
            $invalidProperties[] = "'device' can't be null";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return 0 === count($this->listInvalidProperties());
    }

    /**
     * Gets browser_name.
     *
     */
    public function getBrowserName(): ?string
    {
        return $this->container['browser_name'];
    }

    /**
     * Sets browser_name.
     *
     * @param string $browser_name browser_name
     *
     */
    public function setBrowserName(string $browser_name): self
    {
        $this->container['browser_name'] = $browser_name;

        return $this;
    }

    /**
     * Gets browser_major_version.
     *
     */
    public function getBrowserMajorVersion(): ?string
    {
        return $this->container['browser_major_version'];
    }

    /**
     * Sets browser_major_version.
     *
     * @param string $browser_major_version browser_major_version
     *
     */
    public function setBrowserMajorVersion(string $browser_major_version): self
    {
        $this->container['browser_major_version'] = $browser_major_version;

        return $this;
    }

    /**
     * Gets browser_full_version.
     *
     */
    public function getBrowserFullVersion(): ?string
    {
        return $this->container['browser_full_version'];
    }

    /**
     * Sets browser_full_version.
     *
     * @param string $browser_full_version browser_full_version
     *
     */
    public function setBrowserFullVersion(string $browser_full_version): self
    {
        $this->container['browser_full_version'] = $browser_full_version;

        return $this;
    }

    /**
     * Gets os.
     *
     */
    public function getOs(): ?string
    {
        return $this->container['os'];
    }

    /**
     * Sets os.
     *
     * @param string $os os
     *
     */
    public function setOs(string $os): self
    {
        $this->container['os'] = $os;

        return $this;
    }

    /**
     * Gets os_version.
     *
     */
    public function getOsVersion(): ?string
    {
        return $this->container['os_version'];
    }

    /**
     * Sets os_version.
     *
     * @param string $os_version os_version
     *
     */
    public function setOsVersion(string $os_version): self
    {
        $this->container['os_version'] = $os_version;

        return $this;
    }

    /**
     * Gets device.
     *
     */
    public function getDevice(): ?string
    {
        return $this->container['device'];
    }

    /**
     * Sets device.
     *
     * @param string $device device
     *
     */
    public function setDevice(string $device): self
    {
        $this->container['device'] = $device;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @see https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets a header-safe presentation of the object.
     *
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Array of nullable properties.
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null.
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null.
     *
     * @param bool[] $openAPINullablesSetToNull
     *
     * @codeCoverageIgnore
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array.
     *
     * @noinspection PhpSameParameterValueInspection
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName; // @codeCoverageIgnore
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }
}
