<?php

/**
 * EventEdge.
 *
 * @category Class
 *
 * @author   Fingerprint
 *
 * @see      https://fingerprint.com
 */

/**
 * Server API.
 *
 * Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. The API also supports collection of Automation Intelligence for requests to your server in edge, pre-origin, or middleware contexts.
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Fingerprint\ServerSdk\Model;

use Fingerprint\ServerSdk\ObjectSerializer;

/**
 * IP and bot analysis for an event generated by the Automation Intelligence API (`/edge` endpoint). No client-side collection agent is involved, so Identification (`visitor_id`) and device-telemetry-derived Smart Signals are not available.
 *
 * @category Class
 *
 * @description IP and bot analysis for an event generated by the Automation Intelligence API (&#x60;/edge&#x60; endpoint). No client-side collection agent is involved, so Identification (&#x60;visitor_id&#x60;) and device-telemetry-derived Smart Signals are not available.
 *
 * @author   Fingerprint
 *
 * @see      https://fingerprint.com
 *
 * @implements \ArrayAccess<string, mixed>
 *
 * @noinspection GrazieInspection
 * @noinspection RedundantSuppression
 */
class EventEdge implements ModelInterface, \ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     */
    protected static string $openAPIModelName = 'EventEdge';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static array $openAPITypes = [
        'event_id' => 'string',
        'timestamp' => 'int',
        'linked_id' => 'string',
        'tags' => 'array<string,mixed>',
        'url' => 'string',
        'bot_info' => '\Fingerprint\ServerSdk\Model\BotInfo',
        'ip_info' => '\Fingerprint\ServerSdk\Model\IPInfo',
        'proxy' => 'bool',
        'proxy_confidence' => '\Fingerprint\ServerSdk\Model\ProxyConfidence',
        'proxy_details' => '\Fingerprint\ServerSdk\Model\ProxyDetails',
        'vpn' => 'bool',
        'vpn_confidence' => '\Fingerprint\ServerSdk\Model\VpnConfidence',
        'vpn_methods' => '\Fingerprint\ServerSdk\Model\VpnMethods',
        'source' => '\Fingerprint\ServerSdk\Model\EventSource',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'event_id' => null,
        'timestamp' => 'int64',
        'linked_id' => null,
        'tags' => null,
        'url' => null,
        'bot_info' => null,
        'ip_info' => null,
        'proxy' => null,
        'proxy_confidence' => null,
        'proxy_details' => null,
        'vpn' => null,
        'vpn_confidence' => null,
        'vpn_methods' => null,
        'source' => null,
    ];

    /**
     * Array of nullable properties. Used for (de)serialization.
     *
     * @var bool[]
     */
    protected static array $openAPINullables = [
        'event_id' => false,
        'timestamp' => false,
        'linked_id' => false,
        'tags' => false,
        'url' => false,
        'bot_info' => false,
        'ip_info' => false,
        'proxy' => false,
        'proxy_confidence' => false,
        'proxy_details' => false,
        'vpn' => false,
        'vpn_confidence' => false,
        'vpn_methods' => false,
        'source' => false,
    ];

    /**
     * If a nullable field gets set to null, insert it here.
     *
     * @var bool[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'event_id' => 'event_id',
        'timestamp' => 'timestamp',
        'linked_id' => 'linked_id',
        'tags' => 'tags',
        'url' => 'url',
        'bot_info' => 'bot_info',
        'ip_info' => 'ip_info',
        'proxy' => 'proxy',
        'proxy_confidence' => 'proxy_confidence',
        'proxy_details' => 'proxy_details',
        'vpn' => 'vpn',
        'vpn_confidence' => 'vpn_confidence',
        'vpn_methods' => 'vpn_methods',
        'source' => 'source',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static array $setters = [
        'event_id' => 'setEventId',
        'timestamp' => 'setTimestamp',
        'linked_id' => 'setLinkedId',
        'tags' => 'setTags',
        'url' => 'setUrl',
        'bot_info' => 'setBotInfo',
        'ip_info' => 'setIpInfo',
        'proxy' => 'setProxy',
        'proxy_confidence' => 'setProxyConfidence',
        'proxy_details' => 'setProxyDetails',
        'vpn' => 'setVpn',
        'vpn_confidence' => 'setVpnConfidence',
        'vpn_methods' => 'setVpnMethods',
        'source' => 'setSource',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static array $getters = [
        'event_id' => 'getEventId',
        'timestamp' => 'getTimestamp',
        'linked_id' => 'getLinkedId',
        'tags' => 'getTags',
        'url' => 'getUrl',
        'bot_info' => 'getBotInfo',
        'ip_info' => 'getIpInfo',
        'proxy' => 'getProxy',
        'proxy_confidence' => 'getProxyConfidence',
        'proxy_details' => 'getProxyDetails',
        'vpn' => 'getVpn',
        'vpn_confidence' => 'getVpnConfidence',
        'vpn_methods' => 'getVpnMethods',
        'source' => 'getSource',
    ];

    /**
     * Associative array for storing property values.
     */
    protected array $container = [];

    /**
     * Constructor.
     *
     * @param array|null $data Associated array of property values
     *                         initializing the model
     *
     * @noinspection DuplicatedCode
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('event_id', $data ?? [], null);
        $this->setIfExists('timestamp', $data ?? [], null);
        $this->setIfExists('linked_id', $data ?? [], null);
        $this->setIfExists('tags', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('bot_info', $data ?? [], null);
        $this->setIfExists('ip_info', $data ?? [], null);
        $this->setIfExists('proxy', $data ?? [], null);
        $this->setIfExists('proxy_confidence', $data ?? [], null);
        $this->setIfExists('proxy_details', $data ?? [], null);
        $this->setIfExists('vpn', $data ?? [], null);
        $this->setIfExists('vpn_confidence', $data ?? [], null);
        $this->setIfExists('vpn_methods', $data ?? [], null);
        $this->setIfExists('source', $data ?? [], null);
    }

    /**
     * Gets the string presentation of the object.
     *
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Checks if a property is nullable.
     *
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if (null === $this->container['event_id']) {
            $invalidProperties[] = "'event_id' can't be null";
        }
        if (null === $this->container['timestamp']) {
            $invalidProperties[] = "'timestamp' can't be null";
        }
        if (null === $this->container['ip_info']) {
            $invalidProperties[] = "'ip_info' can't be null";
        }
        if (null === $this->container['source']) {
            $invalidProperties[] = "'source' can't be null";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return 0 === count($this->listInvalidProperties());
    }

    /**
     * Gets event_id.
     *
     */
    public function getEventId(): ?string
    {
        return $this->container['event_id'];
    }

    /**
     * Sets event_id.
     *
     * @param string $event_id Unique identifier of the user's request. The first portion of the event_id is a unix epoch milliseconds timestamp.
     *
     */
    public function setEventId(string $event_id): self
    {
        $this->container['event_id'] = $event_id;

        return $this;
    }

    /**
     * Gets timestamp.
     *
     */
    public function getTimestamp(): ?int
    {
        return $this->container['timestamp'];
    }

    /**
     * Sets timestamp.
     *
     * @param int $timestamp timestamp of the event with millisecond precision in Unix time
     *
     */
    public function setTimestamp(int $timestamp): self
    {
        $this->container['timestamp'] = $timestamp;

        return $this;
    }

    /**
     * Gets linked_id.
     *
     */
    public function getLinkedId(): ?string
    {
        return $this->container['linked_id'];
    }

    /**
     * Sets linked_id.
     *
     * @param string $linked_id a customer-provided id that was sent with the request
     *
     */
    public function setLinkedId(string $linked_id): self
    {
        $this->container['linked_id'] = $linked_id;

        return $this;
    }

    /**
     * Gets tags.
     *
     * @return array<string,mixed>|null
     */
    public function getTags(): ?array
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags.
     *
     * @param array<string,mixed> $tags a customer-provided value or an object that was sent with the identification request or updated later
     *
     */
    public function setTags(array $tags): self
    {
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets url.
     *
     */
    public function getUrl(): ?string
    {
        return $this->container['url'];
    }

    /**
     * Sets url.
     *
     * @param string $url page URL from which the request was sent
     *
     */
    public function setUrl(string $url): self
    {
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets bot_info.
     *
     */
    public function getBotInfo(): ?BotInfo
    {
        return $this->container['bot_info'];
    }

    /**
     * Sets bot_info.
     *
     * @param BotInfo $bot_info bot_info
     *
     */
    public function setBotInfo(BotInfo $bot_info): self
    {
        $this->container['bot_info'] = $bot_info;

        return $this;
    }

    /**
     * Gets ip_info.
     *
     */
    public function getIpInfo(): ?IPInfo
    {
        return $this->container['ip_info'];
    }

    /**
     * Sets ip_info.
     *
     * @param IPInfo $ip_info ip_info
     *
     */
    public function setIpInfo(IPInfo $ip_info): self
    {
        $this->container['ip_info'] = $ip_info;

        return $this;
    }

    /**
     * Gets proxy.
     *
     */
    public function getProxy(): ?bool
    {
        return $this->container['proxy'];
    }

    /**
     * Sets proxy.
     *
     * @param bool $proxy IP address was used by a public proxy provider or belonged to a known recent residential proxy
     *
     */
    public function setProxy(bool $proxy): self
    {
        $this->container['proxy'] = $proxy;

        return $this;
    }

    /**
     * Gets proxy_confidence.
     *
     */
    public function getProxyConfidence(): ProxyConfidence|string|null
    {
        return $this->container['proxy_confidence'];
    }

    /**
     * Sets proxy_confidence.
     *
     * @param ProxyConfidence|string $proxy_confidence proxy_confidence
     *
     */
    public function setProxyConfidence(ProxyConfidence|string $proxy_confidence): self
    {
        $this->container['proxy_confidence'] = $proxy_confidence;

        return $this;
    }

    /**
     * Gets proxy_details.
     *
     */
    public function getProxyDetails(): ?ProxyDetails
    {
        return $this->container['proxy_details'];
    }

    /**
     * Sets proxy_details.
     *
     * @param ProxyDetails $proxy_details proxy_details
     *
     */
    public function setProxyDetails(ProxyDetails $proxy_details): self
    {
        $this->container['proxy_details'] = $proxy_details;

        return $this;
    }

    /**
     * Gets vpn.
     *
     */
    public function getVpn(): ?bool
    {
        return $this->container['vpn'];
    }

    /**
     * Sets vpn.
     *
     * @param bool $vpn VPN or other anonymizing service has been used when sending the request
     *
     */
    public function setVpn(bool $vpn): self
    {
        $this->container['vpn'] = $vpn;

        return $this;
    }

    /**
     * Gets vpn_confidence.
     *
     */
    public function getVpnConfidence(): string|VpnConfidence|null
    {
        return $this->container['vpn_confidence'];
    }

    /**
     * Sets vpn_confidence.
     *
     * @param VpnConfidence|string $vpn_confidence vpn_confidence
     *
     */
    public function setVpnConfidence(string|VpnConfidence $vpn_confidence): self
    {
        $this->container['vpn_confidence'] = $vpn_confidence;

        return $this;
    }

    /**
     * Gets vpn_methods.
     *
     */
    public function getVpnMethods(): ?VpnMethods
    {
        return $this->container['vpn_methods'];
    }

    /**
     * Sets vpn_methods.
     *
     * @param VpnMethods $vpn_methods vpn_methods
     *
     */
    public function setVpnMethods(VpnMethods $vpn_methods): self
    {
        $this->container['vpn_methods'] = $vpn_methods;

        return $this;
    }

    /**
     * Gets source.
     *
     */
    public function getSource(): EventSource|string|null
    {
        return $this->container['source'];
    }

    /**
     * Sets source.
     *
     * @param EventSource|string $source source
     *
     */
    public function setSource(EventSource|string $source): self
    {
        $this->container['source'] = $source;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @see https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets a header-safe presentation of the object.
     *
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Array of nullable properties.
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null.
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null.
     *
     * @param bool[] $openAPINullablesSetToNull
     *
     * @codeCoverageIgnore
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array.
     *
     * @noinspection PhpSameParameterValueInspection
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName; // @codeCoverageIgnore
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }
}
