<?php

/**
 * RuleActionType.
 *
 * PHP version 8.1
 *
 * @category Enum
 *
 * @author   Fingerprint
 *
 * @see      https://fingerprint.com
 */

/**
 * Server API.
 *
 * Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Fingerprint\ServerSdk\Model;

/**
 * Describes the action to take with the request.
 *
 * @category Enum
 *
 * @description Describes the action to take with the request.
 *
 * @author   Fingerprint
 *
 * @see      https://fingerprint.com
 *
 * @noinspection GrazieInspection
 * @noinspection RedundantSuppression
 */
enum RuleActionType: string
{
    case ALLOW = 'allow';
    case BLOCK = 'block';
}
