<?php

/**
 * SearchEventsBotInfo.
 *
 * @category Enum
 *
 * @author   Fingerprint
 *
 * @see      https://fingerprint.com
 */

/**
 * Server API.
 *
 * Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. The API also supports collection of Automation Intelligence for requests to your server in edge, pre-origin, or middleware contexts.
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Fingerprint\ServerSdk\Model;

/**
 * Filter events by their Bot Info result, specifically:
 * - `all` - events where any kind of bot was detected.
 * - `none` - events where no bot was detected.
 *
 * @category Enum
 *
 * @description Filter events by their Bot Info result, specifically:   - &#x60;all&#x60; - events where any kind of bot was detected.   - &#x60;none&#x60; - events where no bot was detected.
 *
 * @author   Fingerprint
 *
 * @see      https://fingerprint.com
 *
 * @noinspection GrazieInspection
 * @noinspection RedundantSuppression
 */
enum SearchEventsBotInfo: string
{
    case ALL = 'all';
    case NONE = 'none';
}
