<?php

/**
 * TamperingConfidence.
 *
 * @category Enum
 *
 * @author   Fingerprint
 *
 * @see      https://fingerprint.com
 */

/**
 * Server API.
 *
 * Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Fingerprint\ServerSdk\Model;

/**
 * The confidence level indicates how certain Fingerprint is that the current request involves browser tampering. This confidence level is determined by evaluating multiple factors, such as heuristic rules, probabilistic anomaly detection, an anti detect browser ml model, and other relevant methods. It is conveyed as a string with possible values such as high, medium, or low
 * In case of tampering: `true`
 * **High confidence**: heuristic anti detect browser signals and the ml model are triggered, or all of the methods are triggered.
 * **Medium confidence**: either the ml model triggers alone, the anomaly score triggers alone with or without the heuristic anti detect browser methods trigger.
 * **Low confidence**: only the heuristic anti detect methods are triggered.
 *
 * In case of tampering: `false`
 * **High confidence:** Strong signals suggest the user is not tampering with their request.
 *
 * @category Enum
 *
 * @description The confidence level indicates how certain Fingerprint is that the current request involves browser tampering. This confidence level is determined by evaluating multiple factors, such as heuristic rules, probabilistic anomaly detection, an anti detect browser ml model, and other relevant methods. It is conveyed as a string with possible values such as high, medium, or low In case of tampering: &#x60;true&#x60; * **High confidence**: heuristic anti detect browser signals and the ml model are triggered, or all of the methods are triggered. * **Medium confidence**: either the ml model triggers alone, the anomaly score triggers alone with or without the heuristic anti detect browser methods trigger. * **Low confidence**: only the heuristic anti detect methods are triggered.  In case of tampering: &#x60;false&#x60; * **High confidence:** Strong signals suggest the user is not tampering with their request.
 *
 * @author   Fingerprint
 *
 * @see      https://fingerprint.com
 *
 * @noinspection GrazieInspection
 * @noinspection RedundantSuppression
 */
enum TamperingConfidence: string
{
    case LOW = 'low';
    case MEDIUM = 'medium';
    case HIGH = 'high';
}
