<?php

/**
 * WebGlBasics.
 *
 * @category Class
 *
 * @author   Fingerprint
 *
 * @see      https://fingerprint.com
 */

/**
 * Server API.
 *
 * Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Fingerprint\ServerSdk\Model;

use Fingerprint\ServerSdk\ObjectSerializer;

/**
 * Render and vendor strings reported by the WebGL context.
 *
 * @category Class
 *
 * @description Render and vendor strings reported by the WebGL context.
 *
 * @author   Fingerprint
 *
 * @see      https://fingerprint.com
 *
 * @implements \ArrayAccess<string, mixed>
 *
 * @noinspection GrazieInspection
 * @noinspection RedundantSuppression
 */
class WebGlBasics implements ModelInterface, \ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     */
    protected static string $openAPIModelName = 'WebGlBasics';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static array $openAPITypes = [
        'version' => 'string',
        'vendor' => 'string',
        'vendor_unmasked' => 'string',
        'renderer' => 'string',
        'renderer_unmasked' => 'string',
        'shading_language_version' => 'string',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'version' => null,
        'vendor' => null,
        'vendor_unmasked' => null,
        'renderer' => null,
        'renderer_unmasked' => null,
        'shading_language_version' => null,
    ];

    /**
     * Array of nullable properties. Used for (de)serialization.
     *
     * @var bool[]
     */
    protected static array $openAPINullables = [
        'version' => false,
        'vendor' => false,
        'vendor_unmasked' => false,
        'renderer' => false,
        'renderer_unmasked' => false,
        'shading_language_version' => false,
    ];

    /**
     * If a nullable field gets set to null, insert it here.
     *
     * @var bool[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'version' => 'version',
        'vendor' => 'vendor',
        'vendor_unmasked' => 'vendor_unmasked',
        'renderer' => 'renderer',
        'renderer_unmasked' => 'renderer_unmasked',
        'shading_language_version' => 'shading_language_version',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static array $setters = [
        'version' => 'setVersion',
        'vendor' => 'setVendor',
        'vendor_unmasked' => 'setVendorUnmasked',
        'renderer' => 'setRenderer',
        'renderer_unmasked' => 'setRendererUnmasked',
        'shading_language_version' => 'setShadingLanguageVersion',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static array $getters = [
        'version' => 'getVersion',
        'vendor' => 'getVendor',
        'vendor_unmasked' => 'getVendorUnmasked',
        'renderer' => 'getRenderer',
        'renderer_unmasked' => 'getRendererUnmasked',
        'shading_language_version' => 'getShadingLanguageVersion',
    ];

    /**
     * Associative array for storing property values.
     */
    protected array $container = [];

    /**
     * Constructor.
     *
     * @param array|null $data Associated array of property values
     *                         initializing the model
     *
     * @noinspection DuplicatedCode
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('version', $data ?? [], null);
        $this->setIfExists('vendor', $data ?? [], null);
        $this->setIfExists('vendor_unmasked', $data ?? [], null);
        $this->setIfExists('renderer', $data ?? [], null);
        $this->setIfExists('renderer_unmasked', $data ?? [], null);
        $this->setIfExists('shading_language_version', $data ?? [], null);
    }

    /**
     * Gets the string presentation of the object.
     *
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Checks if a property is nullable.
     *
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        return [];
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return 0 === count($this->listInvalidProperties());
    }

    /**
     * Gets version.
     *
     */
    public function getVersion(): ?string
    {
        return $this->container['version'];
    }

    /**
     * Sets version.
     *
     * @param string $version version
     *
     */
    public function setVersion(string $version): self
    {
        $this->container['version'] = $version;

        return $this;
    }

    /**
     * Gets vendor.
     *
     */
    public function getVendor(): ?string
    {
        return $this->container['vendor'];
    }

    /**
     * Sets vendor.
     *
     * @param string $vendor vendor
     *
     */
    public function setVendor(string $vendor): self
    {
        $this->container['vendor'] = $vendor;

        return $this;
    }

    /**
     * Gets vendor_unmasked.
     *
     */
    public function getVendorUnmasked(): ?string
    {
        return $this->container['vendor_unmasked'];
    }

    /**
     * Sets vendor_unmasked.
     *
     * @param string $vendor_unmasked vendor_unmasked
     *
     */
    public function setVendorUnmasked(string $vendor_unmasked): self
    {
        $this->container['vendor_unmasked'] = $vendor_unmasked;

        return $this;
    }

    /**
     * Gets renderer.
     *
     */
    public function getRenderer(): ?string
    {
        return $this->container['renderer'];
    }

    /**
     * Sets renderer.
     *
     * @param string $renderer renderer
     *
     */
    public function setRenderer(string $renderer): self
    {
        $this->container['renderer'] = $renderer;

        return $this;
    }

    /**
     * Gets renderer_unmasked.
     *
     */
    public function getRendererUnmasked(): ?string
    {
        return $this->container['renderer_unmasked'];
    }

    /**
     * Sets renderer_unmasked.
     *
     * @param string $renderer_unmasked renderer_unmasked
     *
     */
    public function setRendererUnmasked(string $renderer_unmasked): self
    {
        $this->container['renderer_unmasked'] = $renderer_unmasked;

        return $this;
    }

    /**
     * Gets shading_language_version.
     *
     */
    public function getShadingLanguageVersion(): ?string
    {
        return $this->container['shading_language_version'];
    }

    /**
     * Sets shading_language_version.
     *
     * @param string $shading_language_version shading_language_version
     *
     */
    public function setShadingLanguageVersion(string $shading_language_version): self
    {
        $this->container['shading_language_version'] = $shading_language_version;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @see https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets a header-safe presentation of the object.
     *
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Array of nullable properties.
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null.
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null.
     *
     * @param bool[] $openAPINullablesSetToNull
     *
     * @codeCoverageIgnore
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array.
     *
     * @noinspection PhpSameParameterValueInspection
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName; // @codeCoverageIgnore
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }
}
