<?php
/**
 * WebhookRareDevice.
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Server API v3 (deprecated).
 *
 * > 🚧 Deprecation Notice
 * >
 * > This version of Server API is marked as deprecated starting on **Jan 7th 2026** and will be fully defunct on **Jan 7th 2027** according to our [API Deprecation Policy](https://dev.fingerprint.com/reference/api-deprecation-policy). If you still use this version, please follow our [migration guide](https://dev.fingerprint.com/reference/migrating-from-server-api-v3-to-v4) to migrate from this deprecated version to the new one.
 *
 * Fingerprint Server API allows you to search, update, and delete identification events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios.
 * Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 *
 * OpenAPI spec version: 3
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.78
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Fingerprint\ServerAPI\Model;

use Fingerprint\ServerAPI\ObjectSerializer;

/**
 * WebhookRareDevice Class Doc Comment.
 *
 * @deprecated
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */
class WebhookRareDevice implements ModelInterface, \ArrayAccess
{
    public const PERCENTILE_BUCKET_P95 = '<p95';
    public const PERCENTILE_BUCKET_P95_P99 = 'p95-p99';
    public const PERCENTILE_BUCKET_P99_P995 = 'p99-p99.5';
    public const PERCENTILE_BUCKET_P995_P999 = 'p99.5-p99.9';
    public const PERCENTILE_BUCKET_P999 = 'p99.9+';
    public const PERCENTILE_BUCKET_NOT_SEEN = 'not_seen';

    /**
     * The original name of the model.
     *
     */
    protected static string $swaggerModelName = 'WebhookRareDevice';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static array $swaggerTypes = [
        'result' => 'bool',
        'percentile_bucket' => 'string'];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static array $swaggerFormats = [
        'result' => null,
        'percentile_bucket' => null];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'result' => 'result',
        'percentile_bucket' => 'percentileBucket'];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static array $setters = [
        'result' => 'setResult',
        'percentile_bucket' => 'setPercentileBucket'];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static array $getters = [
        'result' => 'getResult',
        'percentile_bucket' => 'getPercentileBucket'];

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected array $container = [];

    /**
     * Constructor.
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['result'] = isset($data['result']) ? $data['result'] : null;
        $this->container['percentile_bucket'] = isset($data['percentile_bucket']) ? $data['percentile_bucket'] : null;
    }

    /**
     * Gets the string presentation of the object.
     *
     */
    public function __toString(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     */
    public static function swaggerTypes(): array
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     */
    public static function swaggerFormats(): array
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     */
    public function getModelName(): string
    {
        return self::$swaggerModelName;
    }

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public function getPercentileBucketAllowableValues(): array
    {
        return [
            self::PERCENTILE_BUCKET_P95,
            self::PERCENTILE_BUCKET_P95_P99,
            self::PERCENTILE_BUCKET_P99_P995,
            self::PERCENTILE_BUCKET_P995_P999,
            self::PERCENTILE_BUCKET_P999,
            self::PERCENTILE_BUCKET_NOT_SEEN,        ];
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        $allowedValues = $this->getPercentileBucketAllowableValues();
        if (!is_null($this->container['percentile_bucket']) && !in_array($this->container['percentile_bucket'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'percentile_bucket', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return 0 === count($this->listInvalidProperties());
    }

    /**
     * Gets result.
     */
    public function getResult(): ?bool
    {
        return $this->container['result'];
    }

    /**
     * Sets result.
     *
     * @param ?bool $result `true` if the device is considered rare based on its combination of hardware and software attributes.  A device is classified as rare if it falls within the top 99.9 percentile (lowest-frequency segment) of observed traffic,  or if its configuration has not been previously seen (`not_seen`). > This Smart Signal is currently in beta and only available to select customers. If you are interested, please [contact our support team](https://fingerprint.com/support/).
     *
     * @return $this
     */
    public function setResult(?bool $result): self
    {
        $this->container['result'] = $result;

        return $this;
    }

    /**
     * Gets percentile_bucket.
     */
    public function getPercentileBucket(): ?string
    {
        return $this->container['percentile_bucket'];
    }

    /**
     * Sets percentile_bucket.
     *
     * @param ?string $percentile_bucket the rarity percentile bucket of the device, indicating how uncommon the device configuration is compared to all observed devices
     *
     * @return $this
     */
    public function setPercentileBucket(?string $percentile_bucket): self
    {
        $allowedValues = $this->getPercentileBucketAllowableValues();
        if (!is_null($percentile_bucket) && !in_array($percentile_bucket, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'percentile_bucket', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['percentile_bucket'] = $percentile_bucket;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     */
    public function offsetGet($offset): mixed
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int   $offset Offset
     * @param mixed $value  Value to be set
     */
    public function offsetSet($offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object in a pretty JSON format.
     *
     */
    public function toPrettyString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}
