<?php
/**
 * Webhook.
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fingerprint Pro Server API.
 *
 * Fingerprint Pro Server API allows you to get information about visitors and about individual events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * OpenAPI spec version: 3
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Fingerprint\ServerAPI\Model;

use Fingerprint\ServerAPI\ObjectSerializer;

/**
 * Webhook Class Doc Comment.
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */
class Webhook implements ModelInterface, \ArrayAccess
{
    /**
     * The original name of the model.
     *
     */
    protected static string $swaggerModelName = 'Webhook';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static array $swaggerTypes = [
        'request_id' => 'string',
        'url' => 'string',
        'ip' => 'string',
        'tag' => 'array',
        'time' => '\DateTime',
        'timestamp' => 'int',
        'ip_location' => '\Fingerprint\ServerAPI\Model\DeprecatedGeolocation',
        'linked_id' => 'string',
        'visitor_id' => 'string',
        'visitor_found' => 'bool',
        'confidence' => '\Fingerprint\ServerAPI\Model\IdentificationConfidence',
        'first_seen_at' => '\Fingerprint\ServerAPI\Model\IdentificationSeenAt',
        'last_seen_at' => '\Fingerprint\ServerAPI\Model\IdentificationSeenAt',
        'browser_details' => '\Fingerprint\ServerAPI\Model\BrowserDetails',
        'incognito' => 'bool',
        'client_referrer' => 'string',
        'components' => 'array',
        'bot' => '\Fingerprint\ServerAPI\Model\BotdBot',
        'user_agent' => 'string',
        'root_apps' => '\Fingerprint\ServerAPI\Model\WebhookRootApps',
        'emulator' => '\Fingerprint\ServerAPI\Model\WebhookEmulator',
        'ip_info' => '\Fingerprint\ServerAPI\Model\WebhookIPInfo',
        'ip_blocklist' => '\Fingerprint\ServerAPI\Model\WebhookIPBlocklist',
        'tor' => '\Fingerprint\ServerAPI\Model\WebhookTor',
        'vpn' => '\Fingerprint\ServerAPI\Model\WebhookVPN',
        'proxy' => '\Fingerprint\ServerAPI\Model\WebhookProxy',
        'tampering' => '\Fingerprint\ServerAPI\Model\WebhookTampering',
        'cloned_app' => '\Fingerprint\ServerAPI\Model\WebhookClonedApp',
        'factory_reset' => '\Fingerprint\ServerAPI\Model\WebhookFactoryReset',
        'jailbroken' => '\Fingerprint\ServerAPI\Model\WebhookJailbroken',
        'frida' => '\Fingerprint\ServerAPI\Model\WebhookFrida',
        'privacy_settings' => '\Fingerprint\ServerAPI\Model\WebhookPrivacySettings',
        'virtual_machine' => '\Fingerprint\ServerAPI\Model\WebhookVirtualMachine',
        'raw_device_attributes' => 'array',
        'high_activity' => '\Fingerprint\ServerAPI\Model\WebhookHighActivity',
        'location_spoofing' => '\Fingerprint\ServerAPI\Model\WebhookLocationSpoofing',
        'suspect_score' => '\Fingerprint\ServerAPI\Model\WebhookSuspectScore',
        'remote_control' => '\Fingerprint\ServerAPI\Model\WebhookRemoteControl',
        'velocity' => '\Fingerprint\ServerAPI\Model\WebhookVelocity',
        'developer_tools' => '\Fingerprint\ServerAPI\Model\WebhookDeveloperTools',
        'mitm_attack' => '\Fingerprint\ServerAPI\Model\WebhookMitMAttack'];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static array $swaggerFormats = [
        'request_id' => null,
        'url' => null,
        'ip' => null,
        'tag' => null,
        'time' => 'date-time',
        'timestamp' => 'int64',
        'ip_location' => null,
        'linked_id' => null,
        'visitor_id' => null,
        'visitor_found' => null,
        'confidence' => null,
        'first_seen_at' => null,
        'last_seen_at' => null,
        'browser_details' => null,
        'incognito' => null,
        'client_referrer' => null,
        'components' => null,
        'bot' => null,
        'user_agent' => null,
        'root_apps' => null,
        'emulator' => null,
        'ip_info' => null,
        'ip_blocklist' => null,
        'tor' => null,
        'vpn' => null,
        'proxy' => null,
        'tampering' => null,
        'cloned_app' => null,
        'factory_reset' => null,
        'jailbroken' => null,
        'frida' => null,
        'privacy_settings' => null,
        'virtual_machine' => null,
        'raw_device_attributes' => null,
        'high_activity' => null,
        'location_spoofing' => null,
        'suspect_score' => null,
        'remote_control' => null,
        'velocity' => null,
        'developer_tools' => null,
        'mitm_attack' => null];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'request_id' => 'requestId',
        'url' => 'url',
        'ip' => 'ip',
        'tag' => 'tag',
        'time' => 'time',
        'timestamp' => 'timestamp',
        'ip_location' => 'ipLocation',
        'linked_id' => 'linkedId',
        'visitor_id' => 'visitorId',
        'visitor_found' => 'visitorFound',
        'confidence' => 'confidence',
        'first_seen_at' => 'firstSeenAt',
        'last_seen_at' => 'lastSeenAt',
        'browser_details' => 'browserDetails',
        'incognito' => 'incognito',
        'client_referrer' => 'clientReferrer',
        'components' => 'components',
        'bot' => 'bot',
        'user_agent' => 'userAgent',
        'root_apps' => 'rootApps',
        'emulator' => 'emulator',
        'ip_info' => 'ipInfo',
        'ip_blocklist' => 'ipBlocklist',
        'tor' => 'tor',
        'vpn' => 'vpn',
        'proxy' => 'proxy',
        'tampering' => 'tampering',
        'cloned_app' => 'clonedApp',
        'factory_reset' => 'factoryReset',
        'jailbroken' => 'jailbroken',
        'frida' => 'frida',
        'privacy_settings' => 'privacySettings',
        'virtual_machine' => 'virtualMachine',
        'raw_device_attributes' => 'rawDeviceAttributes',
        'high_activity' => 'highActivity',
        'location_spoofing' => 'locationSpoofing',
        'suspect_score' => 'suspectScore',
        'remote_control' => 'remoteControl',
        'velocity' => 'velocity',
        'developer_tools' => 'developerTools',
        'mitm_attack' => 'mitmAttack'];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static array $setters = [
        'request_id' => 'setRequestId',
        'url' => 'setUrl',
        'ip' => 'setIp',
        'tag' => 'setTag',
        'time' => 'setTime',
        'timestamp' => 'setTimestamp',
        'ip_location' => 'setIpLocation',
        'linked_id' => 'setLinkedId',
        'visitor_id' => 'setVisitorId',
        'visitor_found' => 'setVisitorFound',
        'confidence' => 'setConfidence',
        'first_seen_at' => 'setFirstSeenAt',
        'last_seen_at' => 'setLastSeenAt',
        'browser_details' => 'setBrowserDetails',
        'incognito' => 'setIncognito',
        'client_referrer' => 'setClientReferrer',
        'components' => 'setComponents',
        'bot' => 'setBot',
        'user_agent' => 'setUserAgent',
        'root_apps' => 'setRootApps',
        'emulator' => 'setEmulator',
        'ip_info' => 'setIpInfo',
        'ip_blocklist' => 'setIpBlocklist',
        'tor' => 'setTor',
        'vpn' => 'setVpn',
        'proxy' => 'setProxy',
        'tampering' => 'setTampering',
        'cloned_app' => 'setClonedApp',
        'factory_reset' => 'setFactoryReset',
        'jailbroken' => 'setJailbroken',
        'frida' => 'setFrida',
        'privacy_settings' => 'setPrivacySettings',
        'virtual_machine' => 'setVirtualMachine',
        'raw_device_attributes' => 'setRawDeviceAttributes',
        'high_activity' => 'setHighActivity',
        'location_spoofing' => 'setLocationSpoofing',
        'suspect_score' => 'setSuspectScore',
        'remote_control' => 'setRemoteControl',
        'velocity' => 'setVelocity',
        'developer_tools' => 'setDeveloperTools',
        'mitm_attack' => 'setMitmAttack'];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static array $getters = [
        'request_id' => 'getRequestId',
        'url' => 'getUrl',
        'ip' => 'getIp',
        'tag' => 'getTag',
        'time' => 'getTime',
        'timestamp' => 'getTimestamp',
        'ip_location' => 'getIpLocation',
        'linked_id' => 'getLinkedId',
        'visitor_id' => 'getVisitorId',
        'visitor_found' => 'getVisitorFound',
        'confidence' => 'getConfidence',
        'first_seen_at' => 'getFirstSeenAt',
        'last_seen_at' => 'getLastSeenAt',
        'browser_details' => 'getBrowserDetails',
        'incognito' => 'getIncognito',
        'client_referrer' => 'getClientReferrer',
        'components' => 'getComponents',
        'bot' => 'getBot',
        'user_agent' => 'getUserAgent',
        'root_apps' => 'getRootApps',
        'emulator' => 'getEmulator',
        'ip_info' => 'getIpInfo',
        'ip_blocklist' => 'getIpBlocklist',
        'tor' => 'getTor',
        'vpn' => 'getVpn',
        'proxy' => 'getProxy',
        'tampering' => 'getTampering',
        'cloned_app' => 'getClonedApp',
        'factory_reset' => 'getFactoryReset',
        'jailbroken' => 'getJailbroken',
        'frida' => 'getFrida',
        'privacy_settings' => 'getPrivacySettings',
        'virtual_machine' => 'getVirtualMachine',
        'raw_device_attributes' => 'getRawDeviceAttributes',
        'high_activity' => 'getHighActivity',
        'location_spoofing' => 'getLocationSpoofing',
        'suspect_score' => 'getSuspectScore',
        'remote_control' => 'getRemoteControl',
        'velocity' => 'getVelocity',
        'developer_tools' => 'getDeveloperTools',
        'mitm_attack' => 'getMitmAttack'];

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected array $container = [];

    /**
     * Constructor.
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['request_id'] = isset($data['request_id']) ? $data['request_id'] : null;
        $this->container['url'] = isset($data['url']) ? $data['url'] : null;
        $this->container['ip'] = isset($data['ip']) ? $data['ip'] : null;
        $this->container['tag'] = isset($data['tag']) ? $data['tag'] : null;
        $this->container['time'] = isset($data['time']) ? $data['time'] : null;
        $this->container['timestamp'] = isset($data['timestamp']) ? $data['timestamp'] : null;
        $this->container['ip_location'] = isset($data['ip_location']) ? $data['ip_location'] : null;
        $this->container['linked_id'] = isset($data['linked_id']) ? $data['linked_id'] : null;
        $this->container['visitor_id'] = isset($data['visitor_id']) ? $data['visitor_id'] : null;
        $this->container['visitor_found'] = isset($data['visitor_found']) ? $data['visitor_found'] : null;
        $this->container['confidence'] = isset($data['confidence']) ? $data['confidence'] : null;
        $this->container['first_seen_at'] = isset($data['first_seen_at']) ? $data['first_seen_at'] : null;
        $this->container['last_seen_at'] = isset($data['last_seen_at']) ? $data['last_seen_at'] : null;
        $this->container['browser_details'] = isset($data['browser_details']) ? $data['browser_details'] : null;
        $this->container['incognito'] = isset($data['incognito']) ? $data['incognito'] : null;
        $this->container['client_referrer'] = isset($data['client_referrer']) ? $data['client_referrer'] : null;
        $this->container['components'] = isset($data['components']) ? $data['components'] : null;
        $this->container['bot'] = isset($data['bot']) ? $data['bot'] : null;
        $this->container['user_agent'] = isset($data['user_agent']) ? $data['user_agent'] : null;
        $this->container['root_apps'] = isset($data['root_apps']) ? $data['root_apps'] : null;
        $this->container['emulator'] = isset($data['emulator']) ? $data['emulator'] : null;
        $this->container['ip_info'] = isset($data['ip_info']) ? $data['ip_info'] : null;
        $this->container['ip_blocklist'] = isset($data['ip_blocklist']) ? $data['ip_blocklist'] : null;
        $this->container['tor'] = isset($data['tor']) ? $data['tor'] : null;
        $this->container['vpn'] = isset($data['vpn']) ? $data['vpn'] : null;
        $this->container['proxy'] = isset($data['proxy']) ? $data['proxy'] : null;
        $this->container['tampering'] = isset($data['tampering']) ? $data['tampering'] : null;
        $this->container['cloned_app'] = isset($data['cloned_app']) ? $data['cloned_app'] : null;
        $this->container['factory_reset'] = isset($data['factory_reset']) ? $data['factory_reset'] : null;
        $this->container['jailbroken'] = isset($data['jailbroken']) ? $data['jailbroken'] : null;
        $this->container['frida'] = isset($data['frida']) ? $data['frida'] : null;
        $this->container['privacy_settings'] = isset($data['privacy_settings']) ? $data['privacy_settings'] : null;
        $this->container['virtual_machine'] = isset($data['virtual_machine']) ? $data['virtual_machine'] : null;
        $this->container['raw_device_attributes'] = isset($data['raw_device_attributes']) ? $data['raw_device_attributes'] : null;
        $this->container['high_activity'] = isset($data['high_activity']) ? $data['high_activity'] : null;
        $this->container['location_spoofing'] = isset($data['location_spoofing']) ? $data['location_spoofing'] : null;
        $this->container['suspect_score'] = isset($data['suspect_score']) ? $data['suspect_score'] : null;
        $this->container['remote_control'] = isset($data['remote_control']) ? $data['remote_control'] : null;
        $this->container['velocity'] = isset($data['velocity']) ? $data['velocity'] : null;
        $this->container['developer_tools'] = isset($data['developer_tools']) ? $data['developer_tools'] : null;
        $this->container['mitm_attack'] = isset($data['mitm_attack']) ? $data['mitm_attack'] : null;
    }

    /**
     * Gets the string presentation of the object.
     *
     */
    public function __toString(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     */
    public static function swaggerTypes(): array
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     */
    public static function swaggerFormats(): array
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     */
    public function getModelName(): string
    {
        return self::$swaggerModelName;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if (null === $this->container['request_id']) {
            $invalidProperties[] = "'request_id' can't be null";
        }
        if (null === $this->container['url']) {
            $invalidProperties[] = "'url' can't be null";
        }
        if (null === $this->container['ip']) {
            $invalidProperties[] = "'ip' can't be null";
        }
        if (null === $this->container['time']) {
            $invalidProperties[] = "'time' can't be null";
        }
        if (null === $this->container['timestamp']) {
            $invalidProperties[] = "'timestamp' can't be null";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return 0 === count($this->listInvalidProperties());
    }

    /**
     * Gets request_id.
     */
    public function getRequestId(): string
    {
        return $this->container['request_id'];
    }

    /**
     * Sets request_id.
     *
     * @param string $request_id unique identifier of the user's request
     *
     * @return $this
     */
    public function setRequestId(string $request_id): self
    {
        $this->container['request_id'] = $request_id;

        return $this;
    }

    /**
     * Gets url.
     */
    public function getUrl(): string
    {
        return $this->container['url'];
    }

    /**
     * Sets url.
     *
     * @param string $url page URL from which the request was sent
     *
     * @return $this
     */
    public function setUrl(string $url): self
    {
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets ip.
     */
    public function getIp(): string
    {
        return $this->container['ip'];
    }

    /**
     * Sets ip.
     *
     * @param string $ip IP address of the requesting browser or bot
     *
     * @return $this
     */
    public function setIp(string $ip): self
    {
        $this->container['ip'] = $ip;

        return $this;
    }

    /**
     * Gets tag.
     */
    public function getTag(): ?array
    {
        return $this->container['tag'];
    }

    /**
     * Sets tag.
     *
     * @param ?array $tag tag
     *
     * @return $this
     */
    public function setTag(?array $tag): self
    {
        $this->container['tag'] = $tag;

        return $this;
    }

    /**
     * Gets time.
     */
    public function getTime(): \DateTime
    {
        return $this->container['time'];
    }

    /**
     * Sets time.
     *
     * @param \DateTime $time Time expressed according to ISO 8601 in UTC format, when the request from the JS agent was made. We recommend to treat requests that are older than 2 minutes as malicious. Otherwise, request replay attacks are possible.
     *
     * @return $this
     */
    public function setTime(\DateTime $time): self
    {
        $this->container['time'] = $time;

        return $this;
    }

    /**
     * Gets timestamp.
     */
    public function getTimestamp(): int
    {
        return $this->container['timestamp'];
    }

    /**
     * Sets timestamp.
     *
     * @param int $timestamp timestamp of the event with millisecond precision in Unix time
     *
     * @return $this
     */
    public function setTimestamp(int $timestamp): self
    {
        $this->container['timestamp'] = $timestamp;

        return $this;
    }

    /**
     * Gets ip_location.
     */
    public function getIpLocation(): ?DeprecatedGeolocation
    {
        return $this->container['ip_location'];
    }

    /**
     * Sets ip_location.
     *
     * @param ?\Fingerprint\ServerAPI\Model\DeprecatedGeolocation $ip_location ip_location
     *
     * @return $this
     */
    public function setIpLocation(?DeprecatedGeolocation $ip_location): self
    {
        $this->container['ip_location'] = $ip_location;

        return $this;
    }

    /**
     * Gets linked_id.
     */
    public function getLinkedId(): ?string
    {
        return $this->container['linked_id'];
    }

    /**
     * Sets linked_id.
     *
     * @param ?string $linked_id a customer-provided id that was sent with the request
     *
     * @return $this
     */
    public function setLinkedId(?string $linked_id): self
    {
        $this->container['linked_id'] = $linked_id;

        return $this;
    }

    /**
     * Gets visitor_id.
     */
    public function getVisitorId(): ?string
    {
        return $this->container['visitor_id'];
    }

    /**
     * Sets visitor_id.
     *
     * @param ?string $visitor_id string of 20 characters that uniquely identifies the visitor's browser
     *
     * @return $this
     */
    public function setVisitorId(?string $visitor_id): self
    {
        $this->container['visitor_id'] = $visitor_id;

        return $this;
    }

    /**
     * Gets visitor_found.
     */
    public function getVisitorFound(): ?bool
    {
        return $this->container['visitor_found'];
    }

    /**
     * Sets visitor_found.
     *
     * @param ?bool $visitor_found attribute represents if a visitor had been identified before
     *
     * @return $this
     */
    public function setVisitorFound(?bool $visitor_found): self
    {
        $this->container['visitor_found'] = $visitor_found;

        return $this;
    }

    /**
     * Gets confidence.
     */
    public function getConfidence(): ?IdentificationConfidence
    {
        return $this->container['confidence'];
    }

    /**
     * Sets confidence.
     *
     * @param ?\Fingerprint\ServerAPI\Model\IdentificationConfidence $confidence confidence
     *
     * @return $this
     */
    public function setConfidence(?IdentificationConfidence $confidence): self
    {
        $this->container['confidence'] = $confidence;

        return $this;
    }

    /**
     * Gets first_seen_at.
     */
    public function getFirstSeenAt(): ?IdentificationSeenAt
    {
        return $this->container['first_seen_at'];
    }

    /**
     * Sets first_seen_at.
     *
     * @param ?\Fingerprint\ServerAPI\Model\IdentificationSeenAt $first_seen_at first_seen_at
     *
     * @return $this
     */
    public function setFirstSeenAt(?IdentificationSeenAt $first_seen_at): self
    {
        $this->container['first_seen_at'] = $first_seen_at;

        return $this;
    }

    /**
     * Gets last_seen_at.
     */
    public function getLastSeenAt(): ?IdentificationSeenAt
    {
        return $this->container['last_seen_at'];
    }

    /**
     * Sets last_seen_at.
     *
     * @param ?\Fingerprint\ServerAPI\Model\IdentificationSeenAt $last_seen_at last_seen_at
     *
     * @return $this
     */
    public function setLastSeenAt(?IdentificationSeenAt $last_seen_at): self
    {
        $this->container['last_seen_at'] = $last_seen_at;

        return $this;
    }

    /**
     * Gets browser_details.
     */
    public function getBrowserDetails(): ?BrowserDetails
    {
        return $this->container['browser_details'];
    }

    /**
     * Sets browser_details.
     *
     * @param ?\Fingerprint\ServerAPI\Model\BrowserDetails $browser_details browser_details
     *
     * @return $this
     */
    public function setBrowserDetails(?BrowserDetails $browser_details): self
    {
        $this->container['browser_details'] = $browser_details;

        return $this;
    }

    /**
     * Gets incognito.
     */
    public function getIncognito(): ?bool
    {
        return $this->container['incognito'];
    }

    /**
     * Sets incognito.
     *
     * @param ?bool $incognito flag if user used incognito session
     *
     * @return $this
     */
    public function setIncognito(?bool $incognito): self
    {
        $this->container['incognito'] = $incognito;

        return $this;
    }

    /**
     * Gets client_referrer.
     */
    public function getClientReferrer(): ?string
    {
        return $this->container['client_referrer'];
    }

    /**
     * Sets client_referrer.
     *
     * @param ?string $client_referrer client_referrer
     *
     * @return $this
     */
    public function setClientReferrer(?string $client_referrer): self
    {
        $this->container['client_referrer'] = $client_referrer;

        return $this;
    }

    /**
     * Gets components.
     */
    public function getComponents(): ?array
    {
        return $this->container['components'];
    }

    /**
     * Sets components.
     *
     * @param ?array $components components
     *
     * @return $this
     */
    public function setComponents(?array $components): self
    {
        $this->container['components'] = $components;

        return $this;
    }

    /**
     * Gets bot.
     */
    public function getBot(): ?BotdBot
    {
        return $this->container['bot'];
    }

    /**
     * Sets bot.
     *
     * @param ?\Fingerprint\ServerAPI\Model\BotdBot $bot bot
     *
     * @return $this
     */
    public function setBot(?BotdBot $bot): self
    {
        $this->container['bot'] = $bot;

        return $this;
    }

    /**
     * Gets user_agent.
     */
    public function getUserAgent(): ?string
    {
        return $this->container['user_agent'];
    }

    /**
     * Sets user_agent.
     *
     * @param ?string $user_agent user_agent
     *
     * @return $this
     */
    public function setUserAgent(?string $user_agent): self
    {
        $this->container['user_agent'] = $user_agent;

        return $this;
    }

    /**
     * Gets root_apps.
     */
    public function getRootApps(): ?WebhookRootApps
    {
        return $this->container['root_apps'];
    }

    /**
     * Sets root_apps.
     *
     * @param ?\Fingerprint\ServerAPI\Model\WebhookRootApps $root_apps root_apps
     *
     * @return $this
     */
    public function setRootApps(?WebhookRootApps $root_apps): self
    {
        $this->container['root_apps'] = $root_apps;

        return $this;
    }

    /**
     * Gets emulator.
     */
    public function getEmulator(): ?WebhookEmulator
    {
        return $this->container['emulator'];
    }

    /**
     * Sets emulator.
     *
     * @param ?\Fingerprint\ServerAPI\Model\WebhookEmulator $emulator emulator
     *
     * @return $this
     */
    public function setEmulator(?WebhookEmulator $emulator): self
    {
        $this->container['emulator'] = $emulator;

        return $this;
    }

    /**
     * Gets ip_info.
     */
    public function getIpInfo(): ?WebhookIPInfo
    {
        return $this->container['ip_info'];
    }

    /**
     * Sets ip_info.
     *
     * @param ?\Fingerprint\ServerAPI\Model\WebhookIPInfo $ip_info ip_info
     *
     * @return $this
     */
    public function setIpInfo(?WebhookIPInfo $ip_info): self
    {
        $this->container['ip_info'] = $ip_info;

        return $this;
    }

    /**
     * Gets ip_blocklist.
     */
    public function getIpBlocklist(): ?WebhookIPBlocklist
    {
        return $this->container['ip_blocklist'];
    }

    /**
     * Sets ip_blocklist.
     *
     * @param ?\Fingerprint\ServerAPI\Model\WebhookIPBlocklist $ip_blocklist ip_blocklist
     *
     * @return $this
     */
    public function setIpBlocklist(?WebhookIPBlocklist $ip_blocklist): self
    {
        $this->container['ip_blocklist'] = $ip_blocklist;

        return $this;
    }

    /**
     * Gets tor.
     */
    public function getTor(): ?WebhookTor
    {
        return $this->container['tor'];
    }

    /**
     * Sets tor.
     *
     * @param ?\Fingerprint\ServerAPI\Model\WebhookTor $tor tor
     *
     * @return $this
     */
    public function setTor(?WebhookTor $tor): self
    {
        $this->container['tor'] = $tor;

        return $this;
    }

    /**
     * Gets vpn.
     */
    public function getVpn(): ?WebhookVPN
    {
        return $this->container['vpn'];
    }

    /**
     * Sets vpn.
     *
     * @param ?\Fingerprint\ServerAPI\Model\WebhookVPN $vpn vpn
     *
     * @return $this
     */
    public function setVpn(?WebhookVPN $vpn): self
    {
        $this->container['vpn'] = $vpn;

        return $this;
    }

    /**
     * Gets proxy.
     */
    public function getProxy(): ?WebhookProxy
    {
        return $this->container['proxy'];
    }

    /**
     * Sets proxy.
     *
     * @param ?\Fingerprint\ServerAPI\Model\WebhookProxy $proxy proxy
     *
     * @return $this
     */
    public function setProxy(?WebhookProxy $proxy): self
    {
        $this->container['proxy'] = $proxy;

        return $this;
    }

    /**
     * Gets tampering.
     */
    public function getTampering(): ?WebhookTampering
    {
        return $this->container['tampering'];
    }

    /**
     * Sets tampering.
     *
     * @param ?\Fingerprint\ServerAPI\Model\WebhookTampering $tampering tampering
     *
     * @return $this
     */
    public function setTampering(?WebhookTampering $tampering): self
    {
        $this->container['tampering'] = $tampering;

        return $this;
    }

    /**
     * Gets cloned_app.
     */
    public function getClonedApp(): ?WebhookClonedApp
    {
        return $this->container['cloned_app'];
    }

    /**
     * Sets cloned_app.
     *
     * @param ?\Fingerprint\ServerAPI\Model\WebhookClonedApp $cloned_app cloned_app
     *
     * @return $this
     */
    public function setClonedApp(?WebhookClonedApp $cloned_app): self
    {
        $this->container['cloned_app'] = $cloned_app;

        return $this;
    }

    /**
     * Gets factory_reset.
     */
    public function getFactoryReset(): ?WebhookFactoryReset
    {
        return $this->container['factory_reset'];
    }

    /**
     * Sets factory_reset.
     *
     * @param ?\Fingerprint\ServerAPI\Model\WebhookFactoryReset $factory_reset factory_reset
     *
     * @return $this
     */
    public function setFactoryReset(?WebhookFactoryReset $factory_reset): self
    {
        $this->container['factory_reset'] = $factory_reset;

        return $this;
    }

    /**
     * Gets jailbroken.
     */
    public function getJailbroken(): ?WebhookJailbroken
    {
        return $this->container['jailbroken'];
    }

    /**
     * Sets jailbroken.
     *
     * @param ?\Fingerprint\ServerAPI\Model\WebhookJailbroken $jailbroken jailbroken
     *
     * @return $this
     */
    public function setJailbroken(?WebhookJailbroken $jailbroken): self
    {
        $this->container['jailbroken'] = $jailbroken;

        return $this;
    }

    /**
     * Gets frida.
     */
    public function getFrida(): ?WebhookFrida
    {
        return $this->container['frida'];
    }

    /**
     * Sets frida.
     *
     * @param ?\Fingerprint\ServerAPI\Model\WebhookFrida $frida frida
     *
     * @return $this
     */
    public function setFrida(?WebhookFrida $frida): self
    {
        $this->container['frida'] = $frida;

        return $this;
    }

    /**
     * Gets privacy_settings.
     */
    public function getPrivacySettings(): ?WebhookPrivacySettings
    {
        return $this->container['privacy_settings'];
    }

    /**
     * Sets privacy_settings.
     *
     * @param ?\Fingerprint\ServerAPI\Model\WebhookPrivacySettings $privacy_settings privacy_settings
     *
     * @return $this
     */
    public function setPrivacySettings(?WebhookPrivacySettings $privacy_settings): self
    {
        $this->container['privacy_settings'] = $privacy_settings;

        return $this;
    }

    /**
     * Gets virtual_machine.
     */
    public function getVirtualMachine(): ?WebhookVirtualMachine
    {
        return $this->container['virtual_machine'];
    }

    /**
     * Sets virtual_machine.
     *
     * @param ?\Fingerprint\ServerAPI\Model\WebhookVirtualMachine $virtual_machine virtual_machine
     *
     * @return $this
     */
    public function setVirtualMachine(?WebhookVirtualMachine $virtual_machine): self
    {
        $this->container['virtual_machine'] = $virtual_machine;

        return $this;
    }

    /**
     * Gets raw_device_attributes.
     */
    public function getRawDeviceAttributes(): ?array
    {
        return $this->container['raw_device_attributes'];
    }

    /**
     * Sets raw_device_attributes.
     *
     * @param ?array $raw_device_attributes raw_device_attributes
     *
     * @return $this
     */
    public function setRawDeviceAttributes(?array $raw_device_attributes): self
    {
        $this->container['raw_device_attributes'] = $raw_device_attributes;

        return $this;
    }

    /**
     * Gets high_activity.
     */
    public function getHighActivity(): ?WebhookHighActivity
    {
        return $this->container['high_activity'];
    }

    /**
     * Sets high_activity.
     *
     * @param ?\Fingerprint\ServerAPI\Model\WebhookHighActivity $high_activity high_activity
     *
     * @return $this
     */
    public function setHighActivity(?WebhookHighActivity $high_activity): self
    {
        $this->container['high_activity'] = $high_activity;

        return $this;
    }

    /**
     * Gets location_spoofing.
     */
    public function getLocationSpoofing(): ?WebhookLocationSpoofing
    {
        return $this->container['location_spoofing'];
    }

    /**
     * Sets location_spoofing.
     *
     * @param ?\Fingerprint\ServerAPI\Model\WebhookLocationSpoofing $location_spoofing location_spoofing
     *
     * @return $this
     */
    public function setLocationSpoofing(?WebhookLocationSpoofing $location_spoofing): self
    {
        $this->container['location_spoofing'] = $location_spoofing;

        return $this;
    }

    /**
     * Gets suspect_score.
     */
    public function getSuspectScore(): ?WebhookSuspectScore
    {
        return $this->container['suspect_score'];
    }

    /**
     * Sets suspect_score.
     *
     * @param ?\Fingerprint\ServerAPI\Model\WebhookSuspectScore $suspect_score suspect_score
     *
     * @return $this
     */
    public function setSuspectScore(?WebhookSuspectScore $suspect_score): self
    {
        $this->container['suspect_score'] = $suspect_score;

        return $this;
    }

    /**
     * Gets remote_control.
     */
    public function getRemoteControl(): ?WebhookRemoteControl
    {
        return $this->container['remote_control'];
    }

    /**
     * Sets remote_control.
     *
     * @param ?\Fingerprint\ServerAPI\Model\WebhookRemoteControl $remote_control remote_control
     *
     * @return $this
     */
    public function setRemoteControl(?WebhookRemoteControl $remote_control): self
    {
        $this->container['remote_control'] = $remote_control;

        return $this;
    }

    /**
     * Gets velocity.
     */
    public function getVelocity(): ?WebhookVelocity
    {
        return $this->container['velocity'];
    }

    /**
     * Sets velocity.
     *
     * @param ?\Fingerprint\ServerAPI\Model\WebhookVelocity $velocity velocity
     *
     * @return $this
     */
    public function setVelocity(?WebhookVelocity $velocity): self
    {
        $this->container['velocity'] = $velocity;

        return $this;
    }

    /**
     * Gets developer_tools.
     */
    public function getDeveloperTools(): ?WebhookDeveloperTools
    {
        return $this->container['developer_tools'];
    }

    /**
     * Sets developer_tools.
     *
     * @param ?\Fingerprint\ServerAPI\Model\WebhookDeveloperTools $developer_tools developer_tools
     *
     * @return $this
     */
    public function setDeveloperTools(?WebhookDeveloperTools $developer_tools): self
    {
        $this->container['developer_tools'] = $developer_tools;

        return $this;
    }

    /**
     * Gets mitm_attack.
     */
    public function getMitmAttack(): ?WebhookMitMAttack
    {
        return $this->container['mitm_attack'];
    }

    /**
     * Sets mitm_attack.
     *
     * @param ?\Fingerprint\ServerAPI\Model\WebhookMitMAttack $mitm_attack mitm_attack
     *
     * @return $this
     */
    public function setMitmAttack(?WebhookMitMAttack $mitm_attack): self
    {
        $this->container['mitm_attack'] = $mitm_attack;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     */
    public function offsetGet($offset): mixed
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int   $offset Offset
     * @param mixed $value  Value to be set
     */
    public function offsetSet($offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object in a pretty JSON format.
     *
     */
    public function toPrettyString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}
