<?php
/**
 * ResponseVisitsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Fingerprintjs\ServerAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fingerprint Pro Server API
 *
 * Fingerprint Pro Server API provides a way for validating visitors’ data issued by Fingerprint Pro.
 *
 * OpenAPI spec version: 3
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Fingerprintjs\ServerAPI;

/**
 * ResponseVisitsTest Class Doc Comment
 *
 * @category    Class
 * @description ResponseVisits
 * @package     Fingerprintjs\ServerAPI
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ResponseVisitsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ResponseVisits"
     */
    public function testResponseVisits()
    {
    }

    /**
     * Test attribute "request_id"
     */
    public function testPropertyRequestId()
    {
    }

    /**
     * Test attribute "browser_details"
     */
    public function testPropertyBrowserDetails()
    {
    }

    /**
     * Test attribute "incognito"
     */
    public function testPropertyIncognito()
    {
    }

    /**
     * Test attribute "ip"
     */
    public function testPropertyIp()
    {
    }

    /**
     * Test attribute "ip_location"
     */
    public function testPropertyIpLocation()
    {
    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {
    }

    /**
     * Test attribute "time"
     */
    public function testPropertyTime()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "tag"
     */
    public function testPropertyTag()
    {
    }

    /**
     * Test attribute "linked_id"
     */
    public function testPropertyLinkedId()
    {
    }

    /**
     * Test attribute "confidence"
     */
    public function testPropertyConfidence()
    {
    }

    /**
     * Test attribute "visitor_found"
     */
    public function testPropertyVisitorFound()
    {
    }

    /**
     * Test attribute "first_seen_at"
     */
    public function testPropertyFirstSeenAt()
    {
    }

    /**
     * Test attribute "last_seen_at"
     */
    public function testPropertyLastSeenAt()
    {
    }
}
