<?php

/**
 * EdgeRequestTest.
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * Server API.
 *
 * Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. The API also supports collection of Automation Intelligence for requests to your server in edge, pre-origin, or middleware contexts.
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Fingerprint\ServerSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * EdgeRequestTest Class Doc Comment.
 *
 * @category    Class
 *
 * @description HTTP request metadata (including the HTTP method, headers and IP address) sent by you (your server) to the Fingerprint API for IP and bot analysis. To improve accuracy, retain as much of the original semantics of the HTTP request as possible. For example, preserve the order of the request headers and their capitalization. At least one of &#x60;ipv4_address&#x60; or &#x60;ipv6_address&#x60; must be provided; a request with neither is rejected with a &#x60;400&#x60; error. If both IPv4 and IPv6 are provided, IP intelligence will be provided for each address. If an IPv4-mapped IPv6 address is provided in the &#x60;ipv6_address&#x60; request property, the IP intelligence will be provided in the &#x60;ipv4_address&#x60; property of the response.
 *
 * @author      OpenAPI Generator team
 *
 * @see        https://openapi-generator.tech
 *
 * @internal
 *
 * @coversNothing
 */
class EdgeRequestTest extends TestCase
{
    /**
     * Setup before running any test case.
     */
    public static function setUpBeforeClass(): void {}

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass(): void {}

    /**
     * Setup before running each test case.
     */
    public function setUp(): void {}

    /**
     * Clean up after running each test case.
     */
    public function tearDown(): void {}

    /**
     * Test "EdgeRequest".
     */
    public function testEdgeRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "headers".
     */
    public function testPropertyHeaders()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "method".
     */
    public function testPropertyMethod()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "url".
     */
    public function testPropertyUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ipv4_address".
     */
    public function testPropertyIpv4Address()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ipv6_address".
     */
    public function testPropertyIpv6Address()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "linked_id".
     */
    public function testPropertyLinkedId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tags".
     */
    public function testPropertyTags()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
