<?php
/**
 * ApiException
 * PHP version 5
 *
 * @category Class
 * @package  Fingerprint\ServerAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fingerprint Pro Server API
 *
 * Fingerprint Pro Server API allows you to get information about visitors and about individual events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * OpenAPI spec version: 3
 * Contact: support@fingerprint.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Fingerprint\ServerAPI;

use \Exception;
use Fingerprint\ServerAPI\Model\ModelInterface;
use Psr\Http\Message\ResponseInterface;

/**
 * ApiException Class Doc Comment
 *
 * @category Class
 * @package  Fingerprint\ServerAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ApiException extends Exception
{
    protected ResponseInterface $responseObject;
    protected ?ModelInterface $errorDetails = null;
    protected ?int $retryAfter = null;

    public function __construct(?string $message = "", ?int $code = 0)
    {
        parent::__construct($message, $code);
    }


    /**
    * Sets the deseralized response object (during deserialization)
    */
    public function setResponseObject(ResponseInterface $obj): void
    {
        $this->responseObject = $obj;
    }

    public function getResponseObject(): ResponseInterface
    {
        return $this->responseObject;
    }

    public function getErrorDetails(): ModelInterface
    {
        return $this->errorDetails;
    }

    public function setErrorDetails(ModelInterface $errorDetails): void
    {
        $this->errorDetails = $errorDetails;
    }

    public function getRetryAfter(): ?int
    {
        return $this->retryAfter;
    }

    public function setRetryAfter(?int $retryAfter): void
    {
        $this->retryAfter = $retryAfter;
    }
}