name: 'coverage-report'
on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  coverage-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2.37.2
        with:
          php-version: 8.4
          coverage: none
          tools: composer:v2
          extensions: xdebug
      - name: Install Dependencies
        run: composer install -q --profile --ignore-platform-reqs --no-interaction --no-ansi --no-scripts --no-suggest --prefer-dist
      - name: "Create Empty env File for Docker"
        run: touch .env
      - name: PHPUnit
        run: docker compose run --user "$(id -u):$(id -g)" phpunit
      - name: "Parse Coverage"
        run: "php ./generate_coverage_report.php"
      - name: Create Coverage Badges
        uses: jaywcjlove/coverage-badges-cli@998665f7962b1a3935ba8c3e786171a99436e5d1 # v2.3.0
        with:
          source: cov/json/index.json
          output: cov/html/coverage.svg
          jsonPath: total.statements.pct
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          branch: gh-pages
          folder: cov/html
          clean-exclude: |
            .nojekyll