name: test

on:
  push:
    branches-ignore:
      - main

jobs:
  tests:
    name: "PHP ${{ matrix.php_version }}"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php_version: [ "7.3", "7.4", "8.0", "8.1" ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php_version }}"
          coverage: none
          tools: composer:v2
      - name: Install Dependencies
        run: composer install -q --profile --ignore-platform-reqs --no-interaction --no-ansi --no-scripts --no-suggest --prefer-dist
      - uses: php-actions/phpunit@v3
        with:
          php_version: "${{ matrix.php_version }}"
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml.dist
          args: --coverage-text